# DLAI S07A02 - Numpy

In [ ]:
"""
You are now already aware as why we should learn numpy library, so lets understand as how to work with numpy library.

In a brief way, we can say that --> 
The numpy library provides us with an array data structure that has many benefits over Python lists, like:
  It is more compact,
  It is having faster access in reading and writing the items, and
  Its more convenient & efficient to work with.
  s
  
As you might have  already noticed in last video, the NumPy arrays are a bit like Python lists, 
but still very much different at the same time. 

So, lets start with understanding about the array object.

To begin with, I will create an array like this, so that you can get an intuition as how it looks like.
(dont read the code)
"""
import numpy as np
print(np.array([1,2,3,4,5]))

[1 2 3 4 5]


In [ ]:

"""
Okay, this is an example of an array. As you might have guessed already, an Array is nothing but the grid that contains the values 
of the same type.
 
So, this is one of the important difference from the python lists. The python list can contain the values 
which belong to different data types,
But, in case of Numpy arrays, it can have the values which are of the same data type, and it will be numbers.

Got it ?
Yes.

The array which I have created just now, is called as 'One Dimensional Array'

You can Think of an one dimensional array,  as a column or a row, of a table which contains one or more elements init like this.

Now, Apart from sing le dimensional array,
We also have 'Multi Dimensional array'

To build the intuition, you can think of an Excel Spreadsheet — which the data in the form of columns and rows. 
So, thats the 2-d array

To illustrate as how a 2-d array look like, 
I will write the code like this .
(dont read the code)
"""
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
"""
As you can see in the output, the array which I have printed just now has 2 rows & 3 columns.

I hope you now have an idea as how 1d array & 2d array looks like.

During the process of data analysis, one of the common attribute, that is, the property of an array which
we consider before performing any mathematical operation is --> Shape of an array

lets see how we can check the Shape of an array.

to chec k the shape of any array, We call as --> Array_name.shape
So, I will call as :
"""
print(arr1.shape)

(2, 3)


In [ ]:
"""
okay. We have the output that says : 2,3
That means, the array has 2 rows & 3 columns of data.

So, we now know two basic things in Numpy arrays.
that is,how an array looks like, and how to check its shape.

Now, lets proceed to understand as how to create an array.

To create an array using the numpy library, we first have to import the package for our
working.
We import it by running the command like this.
"""
import numpy as np
"""
This line means, we are importing the numpy library for our session,
and instead of calling the complete name as 'numpy' we will be using the short hand as --> 'np'

Okay, I will now execute the code
""";

In [ ]:
"""
Done. this has imported the library.

Now, lets see whether it has been successfully imported or not, by checking its version.

To print the version of numpy we make use of the command as :
(it is double scores in below command)
"""
print(np.__version__) 
#and then I will execute the code

'1.17.3'

In [ ]:
"""
Okay, We have the output that says,
the current version of numpy library running in my system is --> 1.17.3

Guys, one quick note, your version of numpy installed might be different than mine, but the important observation should be,
you should have the some output which displays the version of numpy which is installed in your computer.
Got it ? okay.

Now, lets create a numpy array

To create a new numpy array, we make use of np.array() function, 
and Inside the paranthesis, we will pass the python list or tuple which we want to convert to a numpy array.

To illustrate, I will first create a python list like this
"""
py_list = [1,2,3,4,5,6]

"""
Now, To convert this python list into numpy array,
We simply pass into np.array function like this.
So, I will will call as
"""
py_arr = np.array(py_list)

# Okay, I will now execute the code


In [ ]:
"""
Its done.
Now, lets check the type of the newly created array.
"""
print(type(py_arr))

<class 'numpy.ndarray'>


In [ ]:
"""
As we can see in the output, 
This array is of type 'ndarray'
Which is nothing but  'n dimensional array'.

The function which we have used just now, that is --> np.array,  takes in many parameters.

To see how to use a particular function & its parameters, we just write the required
function, and press the --> (Shift + Tab key) in the keyboard 

now, this has displayed the docstring of numpy.array function. We can display the complete documentaion by
pressing the plus symmbol here.

okay, 
As we can see, these are the parameters that --> np.array function accepts.

As a first parameter it accepts the object. That means, the object, that has to be coverted to numpy array.
Then, the second most important parameter we make use is --> dtype.
This is nothing but the Data type we want to have the array elements 

To illustrate this,
I will write the code like this
"""
py_list = [1,2,3,4,5,6]
py_arr = np.array(py_list, dtype = 'float')
print(py_arr)

"""
As you can observe, 
This time, I have made use of the parameter --> dtype, and set it equal to float.

and then, I have printed the resulting array.

Okay. Lets execute this
""";

[1. 2. 3. 4. 5. 6.]


In [ ]:
"""
As we can see in the output, the resulting array has the elements in the form of floating
point numbers.

In this way,
we can make use of the parameter 'dtype' to specify the data type of the array.

The avaliable data types in Numpy array are:
  Boolean
  Integer
  Float &
  Complex

Got it ? Great.
"""

In [ ]:
"""
So, We have now learnt as how to create a single dimensional array,
Lets see, how we can create a multi dimensional array.

To create a multi dimensional array, we just pass-in the series of lists inside the 
parentheses of np.array function
"""
py_list1 = [1,2,3]
py_list2 = [4,5,6]
arr1 = np.array([py_list1,py_list2],dtype = 'float')
print(arr1)
"""
As you can see,
I am passing the python lists inside the np.array, and specifying the data type to be float.
Okay.
I will now execute this
""";

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
"""
So, we have the resulting array that looks like this.
To confirm whether its 2d array or not,
lets print the shape of the array.
So,
"""
print(arr1.shape)


(2, 3)


In [ ]:
"""
We have the output as --> (2,3)
This means, we have 2 rows and 3 columns

Or we can also interpret the shape as --> the array_1 has 2 indices.
One index runs between 0 and 1, and the other index runs between 0 and 2

Now, Apart from manually passing the elements inside the np.array function,
there are many ways to create numpy arrays.

So ,Lets look at the common methodologies of creating the numpy arrays.

First lets see how we can create an empty array.

To create an array without any element, we make use of --> np.empty function,
and inside the parenethese we will specify the shape of the array we want to generate.
One thing we hae to note is that, we specify the shape inside a tuple. 

To illustrate, I will write the code like this
"""
np.empty((2,1)) 
#So, this will create 1D array of 2 elements,
#okay, I will now execute the code


array([[2.40600563e-316],
       [9.88131292e-324]])

In [ ]:
"""
So We have an output like this,

Like I said already, this has created a empty array. that means, the elements of that array are the 
values present on that memory location

Just to give you more information as how it works,
I will create one more empty array like this
"""
np.empty((5,2,3))

array([[[2.97556371e-316, 9.58487353e-322, 0.00000000e+000],
        [0.00000000e+000, 1.69759663e-313, 2.14027814e+161]],

       [[5.04621383e+180, 4.50618615e-144, 4.27255699e+180],
        [2.91237123e+257, 5.56111702e+180, 2.16385138e+190]],

       [[2.74045673e+180, 1.85494573e-051, 4.08963275e-037],
        [2.12936711e-052, 4.26416525e-096, 9.08366791e+223]],

       [[4.25756448e-096, 9.08366793e+223, 2.80295737e-032],
        [2.21698688e-056, 6.10228910e+170, 3.89337950e-033]],

       [[1.41529402e+161, 9.16651763e-072, 3.67220938e+097],
        [3.89563885e-033, 3.75757692e+126, 1.58268989e-319]]])

In [ ]:
"""
So, this is generated another array of shape --> (5,2,3)

Guys, I just want to re-iterate that,
these methods of creating an array with the use of inbuilt functions of numpy library are very important
You will see me using these in the future sections of this course,So i want you to learn & practice after the completion
of this section.

Now, moving on,
We can Create an array of ones by making use of --> np.ones function,
So it is
"""
arr = np.ones((4,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
"""
As you observed, we are passing the required dimension of array inside the tuple as a first argument.,
and the newly created array has all the elements equal to 1

Now, If I display the shape of newly created array, This is of shape 4,3
"""
arr.shape

(4, 3)

In [ ]:
"""
Similary,
We can create an array of zeros like this.
"""
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
"""
Most of the inbuilt functions of creating an array has the first parameter as shape of the required array,
hence we are passing the required shape of array inside the tuple for this as well.
this array, has all the elements equal to zero

One more very commonly used function to generate the array is --> np.random.random() function.

So ,We can create an array with random values by making use of the random module of numpy like this
"""
print(np.random.random((3,3)))
                 
"""
So, this will generate an array with random numbers between 0 and 1, and the array will be of shape (3,3)
I will now execute the code
""";

[[0.56116812 0.40734552 0.21594291]
 [0.23434276 0.28444691 0.43767692]
 [0.29633026 0.75904662 0.28888758]]


In [ ]:
"""
We can also create the array with same values by making use of np.full function

For the np.full function,
as a first parameter we specify the shape of the resultant array inside the tuple, and 
we specify the second parameter to be equal to 'value' that should be filled inside the array.

For example,
If I write as :
"""
print(np.full((2,3),5))
"""
This will generate the array of shape - 2,3
and, all the elements will be equal to 5

lets test it out
""";

[[5 5 5]
 [5 5 5]]


In [ ]:
"""
okay, as we can see in the output.
The resulting array is of shape --> 2,3
and, all the elements of the array is equal to 5.

Another very common way of generating a numpy array is, with the use of arange function

The arange function in numpy, works similar to range function which we have seen in the section of
core python

The syntax of arange function is :
numpy.arange(start, end, step, data type)

So, if i call as :
"""
print(np.arange(5,15))
"""
This will generate the numpy array with elements between 5 and 15
and here, just like range function,
the number  --> 5 is inclusive, and the number 15 is exclusive.
Lets execute the code
""";

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
"""
As we can see in the output, this has generated the array with numbers between 5 and 15, that is , till 14

Now, If I call the arange function like this.
that is,
"""
print(np.arange(4))

[0 1 2 3]


In [ ]:
"""
This has genreated an array between 0 and 4

That means, if we enter only one value inside the --> np.arange function,
the system will set the default start value as --> zero,and generate a numpy array with the values till the number specified.

Now, this time, I will pass-in one more parameter, that is --> step size 
So will write as,
"""
print(np.arange(5,120,10))
#Okay. I will now execute the code

[  5  15  25  35  45  55  65  75  85  95 105 115]


In [ ]:
"""
As we can see in the output,
this has generated an array with values between 5 and 120, with step size of 10.
So in this way, we make use of the np.arange function to generate the required array.

Apart from this function,
we have np.linspace function.

We use it quite a lot of times when we are plotting a curve in matplotlib library

the syntax of np.linspace function is : numpy.linspace(first point, last point, number of points)
For example, if I call as :
"""
print(np.linspace(5,10,20))
# and then execute the code

[ 5.          5.26315789  5.52631579  5.78947368  6.05263158  6.31578947
  6.57894737  6.84210526  7.10526316  7.36842105  7.63157895  7.89473684
  8.15789474  8.42105263  8.68421053  8.94736842  9.21052632  9.47368421
  9.73684211 10.        ]


In [ ]:
"""
Okay, as we can see in the output,
This has generated 20 equally spaced points between the values 5 & 10.

Finally, we can also create identity matrix with the use of np.eye function.

The way we call this function, np.eye, and inside the parenthese
we will specify the shape of the required matrix.
So, I will write as :
"""
print(np.eye(4,4))
#and then, execute the code

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
"""
So, this has created an identity matrix of size 4,4 with diagonal elements equal to 1.

So this was about the creating different arrays using the numpy library.
I highly recommend you to practice these methods of creating numpy arrays as we will be making use of these concepts in future sections of
deep learning while creating the array for weights and biases and instantiating to some random values.

So, this is very very important guys.

Lets continue more on Numpy from the next video. See you then.
"""

# DLAI S07A03 - Resize & Reshape of arrays

In [ ]:
"""
In the last video we have learnt as how we create THE arrays using numpy library.

Like I mentioned already, One of the common & most important attribute we use in array object is --> 
'shape' of an array.
So, I will write it like this
"""
import numpy as np
arr1 = np.random.random((5,3))
#Now, I will print the shape of the array_1 along with its elements. So,
print(arr1.shape)
print(arr1)

(5, 3)
[[0.36871654 0.1742937  0.16902692]
 [0.33828518 0.51729789 0.02745121]
 [0.17358681 0.40508906 0.65721506]
 [0.26081159 0.94002107 0.72679414]
 [0.29643776 0.47728916 0.44326029]]


In [ ]:
"""
Okay.
We now the have output which displays the shape of the array_1 as --> 5,3

In deep learning or machine learning, One of the common operation we perform is --> modifying the shape of
an array to the required shape so that, we can perform the required mathematical operation.

Now, To change the shape of the array, we have two methods available in numpy array.
They are --> Resize & Reshape

The Resize & Reshape are the commonly used methods which are present inside the numpy package.

So, lets start with learning how to use resize method.

I will now call the resize method on array_1 like this -->
"""
arr2 = np.resize(arr1,(15,1))
print(arr2)

"""
That means, we call the resize method as --> np (dot) resize, and inside the parentheses
we will specify the array name which we are modifying as a first argument,
and required shape of the new array inside a tuple as second argument. 
Okay ?
yes. here I have specified the required new shape as --> (15,1)

I will now execute the code

"""

[[0.36871654]
 [0.1742937 ]
 [0.16902692]
 [0.33828518]
 [0.51729789]
 [0.02745121]
 [0.17358681]
 [0.40508906]
 [0.65721506]
 [0.26081159]
 [0.94002107]
 [0.72679414]
 [0.29643776]
 [0.47728916]
 [0.44326029]]


In [ ]:
"""
As we can see in the output, we have changed the shape of the array_1 from (5,3) to (15,1) as per our
required dimension of the array.
Now, If I call the shape attribute of the array_2 as:
"""
arr2.shape

(15, 1)

In [ ]:
"""
We have the output as --> (15,1)
I hope you now have an idea as how we can how we can apply resize method on an array

Here, One of the important property is,
If we apply the resize on our array with larger dimensions than the one which our array has,
Then, the new array which gets created, will be filled with copies of the original array.

This process of filling with copies of original array are repeated as many times as it is needed.
To illustrate the same,
lets consider the same array_1
First, I will print its elements,along with its shape. So,
"""
print(arr1)
print(arr1.shape)

[[0.36871654 0.1742937  0.16902692]
 [0.33828518 0.51729789 0.02745121]
 [0.17358681 0.40508906 0.65721506]
 [0.26081159 0.94002107 0.72679414]
 [0.29643776 0.47728916 0.44326029]]
(5, 3)


In [ ]:
"""
Okay, this is how the elements inside the array_1 looks like, and has the shape of (5,3)
that means, the arrays has total of 15 elements

Now, lets say, I will call the resize function like this
"""
arr3 = np.resize(arr1,(6,4))
print(arr3)

"""
So, this time,
I am trying to resize the array_1 which has the shape of (5,3)
into a new array of shape (6,4)

Now, lets see what happens, I will now execute the code
""";

[[0.36871654 0.1742937  0.16902692 0.33828518]
 [0.51729789 0.02745121 0.17358681 0.40508906]
 [0.65721506 0.26081159 0.94002107 0.72679414]
 [0.29643776 0.47728916 0.44326029 0.36871654]
 [0.1742937  0.16902692 0.33828518 0.51729789]
 [0.02745121 0.17358681 0.40508906 0.65721506]]


In [ ]:
"""
Okay.

As we can see in the output, 
the array_2 is now created, and it has the shape of (6,4)

but, if you observe the elements, after the 15 elements of the array_1, the elements 
are again filled from first so that, it would match the required dimension of (6,4)

I hope you now have an idea as how resize function works in python.

Apart from resize function, we can change the shape of array, by making use of 'reshape' function.
But one thing we have to keep in mind while using the reshape function is,
The total size of new array should match with the original array.

Let me write the program to explain this.

Suppose if I have an array of size 6,3 
Say,
"""
arr4 = np.random.random((6,3))
#dont read below two lines
print(arr4.shape)
print(arr4)

(6, 3)
[[0.24235399 0.08473531 0.08835072]
 [0.46556044 0.33182572 0.29698058]
 [0.55916307 0.58409219 0.59146794]
 [0.15695336 0.91201059 0.32379207]
 [0.92060936 0.76012151 0.60868017]
 [0.70821279 0.40753098 0.60688967]]


In [ ]:
"""
So, this is the array 4, and it has the shape of (6,3) .
That means, the total number of elements is --> (6*3) which is equal to 18.

So, the possible dimensions to which we can transform these 18 elements are (2,9) ,  (9,2) ,   (3,6)   (18,1) , (1,18),   (3,3,2) , and so on.
that means, it can only be transformed to the shape which has the total number of elements is equal to 18

Now, I will call the reshape function like this
"""
arr5 = np.reshape(arr4,(3,3,2))
print(arr5.shape)
print(arr5)

(3, 3, 2)
[[[0.24235399 0.08473531]
  [0.08835072 0.46556044]
  [0.33182572 0.29698058]]

 [[0.55916307 0.58409219]
  [0.59146794 0.15695336]
  [0.91201059 0.32379207]]

 [[0.92060936 0.76012151]
  [0.60868017 0.70821279]
  [0.40753098 0.60688967]]]


In [ ]:
"""
As we can see in the output,
the shape of the new array_5 is (3,3,2)
and, it has just re arranged the values in array_4 so that , it matches with dimensions
of new array.

We were able to perform the reshape because, the total number of elements in the new array is same
as the original one.

Now, Lets say I will call as :
"""
arr6 = np.reshape(arr4,(6,4))
print(arr6)
print(arr6.shape)
"""
So, this time,
I am trying to reshape the arr4 which has 18 elements into the shape as --> 6,4
that is, 24 elements

lets see what happens, 
okay. I will now execute the code
""";

ValueError: ignored

In [ ]:
"""
We now have the error.
it says --> cannot reshape array of size 18 into shape (6,4)

In most of our coding for deep learning, we will be making use of reshape function in our programs
because, by making use of the reshape, we will not be modifying the total number of elements when we are using the reshape function.

So, this is also one of the important function we use from numpy library

Now, apart from calling the reshape function like --> np.reshape, we can also call the reshape function as --> 
array_name(dot)reshape ,  and specify the required shape inside the parenetheses.

To illustrate, I will write as :
"""
arr6 = arr4.reshape(3,6)
print(arr6)
print(arr6.shape)

[[0.24235399 0.08473531 0.08835072 0.46556044 0.33182572 0.29698058]
 [0.55916307 0.58409219 0.59146794 0.15695336 0.91201059 0.32379207]
 [0.92060936 0.76012151 0.60868017 0.70821279 0.40753098 0.60688967]]
(3, 6)


In [ ]:
"""
As we can see in the output,
we have successfuly changed the shape of array_4 to (3,6), and it behaved just like np.reshape() function


Now, One of the common way that you would see me using the reshape function is, with the combination with 
'arange' function like this.
To illustrate i will write as
"""
arr6 = np.arange(0,100,5).reshape(5,4)
print(arr6)
print(arr6.shape)
"""
So , This time,
I have generated the array 6 using the 'arange' function with start value as 0, end value as 100,
and step size as 5

So, this would have 20 elements in the array.
I have then called the reshape function on it, to change the shape of the array to --> (5,4)
Lets execute it, and verify the result
""";

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]
 [80 85 90 95]]
(5, 4)


In [ ]:
"""
okay, you can see the same in the output.

I hope you now have an idea as how to make use of reshape & resize function on Numpy arrays.
Lets continue our learning in next video
"""

# DLAI S07A04 - Slicing

In [ ]:
"""
In this video we are going to understand how to perform slicing on numpy arrays

We are already aware of the concept of slicing

Slicing is nothing but --> returning a required sample from the given list or sequence

In case of Numpy arrays as well, 
We will just pass the index we are interested in returning, inside the square brackets.

So , lets say, we have an array like this
"""
arr1 = np.arange(0,50,5)
print(arr1)

[ 0  5 10 15 20 25 30 35 40 45]


In [ ]:
"""
The array has elements between 0 and 50 with step size as 5.
Now, lets say we are interested in returning the element at 4th index in array_1
then, we will simply call as :
"""
print(arr1[4])

20


In [ ]:
"""
So, We now have the output as 20.

As you might have observed already, 
4th index refer to value '20' in the array_1

this is because, the indexing starts from zero for numpy arrays as well.

The concept of slicing which we had learnt for python lists will work for numpy arrays as well

So,
If I call as :
"""
print(arr1[2:8])
#and execute the code

[10 15 20 25 30 35]


In [ ]:
"""
We have returned the array with elements between 2nd and 8th index of the array. And, 
just like python lists, in case of numpy arrays as well, the 2nd index is inclusive and 8th index is exclusive

In numpy arrays, We can also specify the step size increment as per our requirement.
So, If I call as -->
"""
print(arr1[1:9:2])



[ 5 15 25 35]


In [ ]:
"""
This has returned the elements between 1st and 9th index with step size as 2.
So, the returned array has the elements as --> 5,15,25 & 35

With this we can say that, 
the concept of slicing which we had learnt for python lists will work exactly same for the Single dimensional numpy arrays.

Now, what about multi dimensional array ?
Well, in case of multi-dimensional array, the concept of index works the same,
But we just have to specify a slice for each dimension of the array.

lets say, we have an array like this
"""
arr2 = np.arange(0,200,10).reshape(4,5)
print(arr2)

[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]]


In [ ]:
"""
This array_2 is of shape --> (4,5)

now, lets apply the concept of slicing for this multi dimensional array.

This time, I will call as :
"""
print(arr2[2])

[100 110 120 130 140]


In [ ]:
"""
So, We have the output which prints the entire row which has the index of 2.
hence we have the elements of the returned array as --> [100 110 120 130 140]

Now, If we want to return a single value instead of  entire row,
Then, We must specify a slice for each dimension of the array.

To understand this, Lets say,
We want to return the value 60 from the array_2

Then, In that case,
We will write it like this.

"""
print(arr2[1,1])
#We are writing like this, because, the value 60 is at index 1 of row index, and at index 1, on the column index.
#Okay. I will now execute this

60

In [ ]:
"""
So, this has returned the value as 60

We can also make use of colon notation to specify the range in each of dimension of the array.
To illustrate i will write the code like this:
"""
arr2[0:4:2,1:4:2]
#and then execute the code

array([[ 10,  30],
       [110, 130]])

In [ ]:
"""
We have the output with elements as --> 10,110,30 & 130
let me display the array_2 again, so that you can clear understanding as why we have got this output.
"""
print(arr2)

[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]]


In [ ]:
"""
Now, lets analyze the slicing logic we have written,
For the row index we have written as --> 0:4:2
That means, start with 'zero' index, till '4th' index row , with step size as 2

So, this would result in selection of 'zeroth' row, and 2nd row like this. 
This time I will enter only the row index part so
that you can understand how it selected particular rows.
So,
"""
arr2[0:4:2,:]

array([[  0,  10,  20,  30,  40],
       [100, 110, 120, 130, 140]])

In [ ]:
"""
So, we have this array as a result of applying the first part of slicing.

Now, 
Now, for the column index,
we had written as --> 1:4:2
That means, start with '1st' index, till '4th' index column , with step size as 2

So, this would result in selection of '1st' column, and 3rd column from the above slice
"""
arr2[0:4:2,1:4:2]

array([[ 10,  30],
       [110, 130]])

In [ ]:
"""
So, we have the output with elements as --> 10,30, 110 & 130

I hope you now have an idea as how slicing works in numpy array.

Lets continue our learning from next video
"""

# DLAI S07A05 - Broadcasting

In [ ]:
"""
We now know as how to create a numpy array, and return the required part of it by making use 
of the concept of slicing, and also reshaping the array as per our requirement.

Now, Like I said already in the first video, one of the main reasons we use Numpy library is,
to perform the mathematical operations efficiently on a large data. 

These mathematical operations are straight forward when we have two arrays of same shape, but in case of 
Machine learning & Deep learning, more often we will be required to work with different shapes of arrays.
Like, Multiplying a Large Array with Smaller array ,
Or adding them or subtracting them, and so on..

Now to decide whether we can perform a particular mathematical operation on an array or not, we should be
aware of the concept called - 'Broadcasting' .Lets see how broadcasting works in numpy

To be able to perform the broadcasting, there are some simple rules which we need to follow.

1 simple rule is, 
Whenever we are performing any arithmetic operation between two arrays,
then, to broadcast successfully, We have to make sure that the shapes of the two arrays should match.

To illustrate this,
lets say we have two arrays like this.
"""
import numpy as np
x = np.random.random((5,3))
y = np.arange(0,15).reshape(5,3)
print(x)
print(y)

[[0.09216799 0.67835743 0.58295118]
 [0.53387582 0.09757996 0.50755733]
 [0.52247772 0.27549629 0.94894125]
 [0.51321901 0.78980027 0.71380152]
 [0.37120947 0.8010632  0.15755128]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
"""
So,
We have now created two arrays 'x' and 'y' with shape as (5,3) 
Since the two shapes match, we can perform mathematical operation between them.
To illustrate , i will perform the mathematical operation as :
"""
result = x + y
print(result)
#and then execute the code

[[ 0.91227149  1.16725869  2.20893307]
 [ 3.54477935  4.76945623  5.52197436]
 [ 6.938418    7.25541506  8.36462129]
 [ 9.86395252 10.31309058 11.47851614]
 [12.89318058 13.13281322 14.72674874]]


In [ ]:
"""
Okay, we have the output as an array like this
The resulting array is the addition of individual elements of the arrays.

Now what happens when we want to perform mathematical operations between two arrays which are of different shapes.
How can we check whether it is possible to broadcast or not ? and, if the broadcasting is possible, what will
be the resulting shape of the array.

To analyze whether the broadcasting is possible or not, 
We apply these 3 rules of broadcasting.

Rule 1, it says: If the two arrays differ in their number of dimensions, then the shape of the one with fewer 
dimensions is padded with ones on its leading left side.
Rule 2 says: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1
       in that dimension is stretched to match the other shape.
Finally, Rule 3: If in any dimension, the sizes disagree and neither is equal to 1, an error is raised. 
That means, Broadcasting is not possible


Lets start working out on these rules to build our foundation on Array broadcasting

Lets consider this simple example,
"""
x = np.random.random((4,3)) 
y = np.arange(3)
print(x.shape)
print(y.shape)

(4, 3)
(3,)


In [ ]:
"""
So, We have shape of  array 'x' as --> 4,3
and array 'y' is of shape --> (3, blank)

Now, we have to check whether broadcasting of arrays is possible or not, so that we can perform
any mathematical operation on it.

So, Lets analyze it based on the rules of broadcasting.

So, the first rule says if the two arrays differ in their number of dimensions, 
then the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

In our case,
The Dimensions of X and Y do not match.
because, as we can clearly see, Array 'x' is a 2 dimensional array, that means it has both rows & columns,
and the array 'y' is of single dimension as it has only one index representing its shape.

So we can say that, the array 'y' has fewer dimensions as compared to that of 'x'

So,
As per 1st rule, we pad the array Y on the left side,
so that the two dimensions would match.

Now, After padding on the left side of array 'y',
the shape of array 'Y' will become,
(1,3)

Okay,
After the application of 1st rule of broadcasting, 
The shapes of X and Y are : (4,3) and (1,3) respectively

Now, the first rule follows,
that means, both the dimensions of x & y matches, that is, both are having 2 dimensions.

So, Lets apply the rule 2.
Rule 2 says, If the shape of the two arrays does not match in any dimension, the array with shape equal 
to 1 in that dimension is stretched to match the other shape.

In our case,
we can observe that, shapes of x and y do not match.
because the shapes are --> (4,3) & (1,3)

We can also observe that, The shape of y on one of the particular dimension is equal to 1 .

So as per the second rule, we stretch that particular dimension, to match as that of dimension x.
So, after stretching, the shape of array --> 'y' would become (4,3)

Since both the Arrays matches in size, 
We can say that,
The arrays 'X' & 'Y' are compatible to perform the arithmetic operation, and the resultant array would be of shape (4,3)

To test the same,
Lets perform multiplication, and verify the shape of the resultant array

So,
I will write as :
"""
result = x * y
print(result.shape)

(4, 3)


In [ ]:
"""
As we can see in the output we have the resultant array of shape --> (4,3)

Lets continue our working on this to make our understanding stronger.

Lets say, we have the array x with shape as (3,7)
And we have the shape of array 'y' as (7,blank)

Now, Lets apply the rules and check the whether broadcasting is possible or not

Lets start with Rule 1,
So, As per the rule 1, if  the two arrays differ in their number of dimensions,
 the shape of the one with fewer dimensions is padded with ones on its leading left side.

 If we look at our example, we have to pad the array 'y' on its left side
 to match the dimension as that of 'x'

So,
This would result in shapes of array x & y as -->  (3,7) and (1,7)

Now the dimensions of X and Y matches.

Lets apply the rule 2,
The Rule 2 says - If the shape of the two arrays does not match in any dimension, 
the array with shape equal to 1 in that dimension is stretched to match the other shape.

So, we stretch the value equal to 1 in array 'y', to match the shape of the other array.
This time, We stretch the 1 to be equal to 3

Okay. We can now see that, both x and y are of shape 3,7 
Since both the shapes are equal.
We can say that,
Broadcasting is possible

Lets verify the same by coding in Python
(dont read the code)
"""
x = np.arange(0,21).reshape(3,7)
y = np.random.random((7))
result = x/y 
print(result.shape)

(3, 7)


In [ ]:
"""
Yes. 
As we can verify from the result,
We can say as, array broadcasting is possible between x and y

I hope you now have an idea as how to apply the rules of broadcasting.

Now, Lets consider a negetive case,

lets say --> array X is of shape 5,3 and y is of shape (4, blank)

Now,
After applying the 1st rule,
That is,
Padding on the left when the dimensions do not match.

We get x and y shapes as → (5,3) , and (1,4)

okay, After applying the rule 1, the dimensions of x and y matches

Now, As per the second rule,
We stretch the 1 in shape of Y to match the other shape of array.

So, after applying the rule 2,
 We can see that, the resulting shapes of x and y are --> (5,3) and (5,4) respectively

As we can see, the shapes 'x'  & 'y' , do not match, Hence, As per the Rule 3,  we say that broadcasting is not possible

So, lets test it out by coding in python.
(dont read the code)
"""
x = np.arange(0,30,2).reshape(5,3)
y = np.arange(0,40,10)
print(x.shape)
print(y.shape)
result = x * y

(5, 3)
(4,)


ValueError: ignored

In [ ]:
"""
Okay, I have created two arrays x and y, with shapes as --> (5,3) & (4,blank)
I have now tried to perform a mathematical operation on it.

now, when I execute the code, we have the result that says :
"operands could not be broadcast together with shapes (5,3) (4, blank) "

This reinforces our understanding as how broadcasting works with numpy arrays.

The concept of broadcasting not only works on 2 dimensional arrays, but it can be
applied to any dimensional array operation

This time, Lets consider this example.

lets say, we have
X is of shape: (4,5) , and y is of shape of (7,4,1)

Now we have to analyze whether the broadcasting is possible or not

One clear observation we can make is that,

array X is 2 dimensional , and array 'Y' is 3 dimensional.

Since the dimensions of x & y arrays do not match,
As per the rule 1,
We pad with ones on the left side of the array which has fewer dimensions.

So, After applying the rule 1,
We have shapes of X & Y as (1,4,5) and (7,4,1) respectively

Now the dimensions of both the arrays match,
Lets apply the rule 2.

Now, As per Rule 2,
We stretch the 1 in the array to match the shape other array.

So, if we apply the rule 2 on the arrays --> x and y,
We will stretch the 1 in x to the value 7, so that it matches the shape of array 'Y' in that dimension.

Similarly,
We stretch 1 in Y to the value 5, so that it matches the shape of array 'X' in that dimension

So, After the application of rule 2,
Both X and Y will be of shapes,
(7,4,5) 

Since the shapes are same, we can say that --> Broadcasting is possible

Lets code it in python to verify this.

(pause 2 seconds)
okay, I have written the code like this
(dont read the code)
"""
x = np.random.random((4,5))
y = np.ones((7,4,1))
result = x + y
print(result.shape)


(7, 4, 5)


In [ ]:
"""
Okay,
we have the resulting array of shape --> (7,4,5)
this is the exact shape we have got when we applied the rules of broadcasting manually.

I hope you are now clear as how Broadcasting works in Numpy python

In the next video, we are going to understand about different mathematical operations we can perform on numpy arrays.
"""A06

# DLAI S07A06 - Mathematical operations & functions in Numpy arrays

In [ ]:
"""
In this video,
We are going to understand what are the different mathematical operation we can perform on Numpy arrays
To illustrate, I will create two arrays, x & y like this
"""
x = np.arange(1,51,5).reshape(2,5)
y = np.arange(1,6)
print(x)
print(y)
print(x.shape)
print(y.shape)

#Okay, I will now execute the code

[[ 1  6 11 16 21]
 [26 31 36 41 46]]
[1 2 3 4 5]
(2, 5)
(5,)


In [ ]:
"""
So, We have X and Y arrays like this.
X is of shape --> (2,5)
y is of shape (5,blank)

As per the rules of broadcasting which we had learnt in previous section,
the shapes of x and y are compatible for mathematical operation.
okay, lets se what are the different mathematical operation we can perform on it.

To do any mathematical operation, We can simply make use of the respective mathematical operator on it.

To illustrate, I will perform addition like this
"""
x + y

array([[ 2,  8, 14, 20, 26],
       [27, 33, 39, 45, 51]])

In [ ]:
"""
So, we have the resulting array of x+y, 
In the same way, Subtraction
"""
x - y

array([[ 0,  4,  8, 12, 16],
       [25, 29, 33, 37, 41]])

In [ ]:
#multiplication
x*y

array([[  1,  12,  33,  64, 105],
       [ 26,  62, 108, 164, 230]])

In [ ]:
#division
x/y

array([[ 1.        ,  3.        ,  3.66666667,  4.        ,  4.2       ],
       [26.        , 15.5       , 12.        , 10.25      ,  9.2       ]])

In [ ]:
#exponentiation
x^y

array([[ 0,  4,  8, 20, 16],
       [27, 29, 39, 45, 43]])

In [ ]:
#Remainder
x%y

array([[0, 0, 2, 0, 1],
       [0, 1, 0, 1, 1]])

In [ ]:
"""
As you have observed, it is very easy to make use of numpy array to perform a mathematical operation,

Now, apart from making use of mathematical operators, numpy has provided many in-built functions
to perform the same operation on arrays.
We have np.add() function to perform additon.
To make use of the function, we simply pass the arrays inside the parentheses like this
"""
np.add(x,y)

array([[ 2,  8, 14, 20, 26],
       [27, 33, 39, 45, 51]])

In [ ]:
#So this has performed the addition of arrays,x & y
##Similary we have np.subtract() function to perform subtraction
np.subtract(x,y)

array([[ 0,  4,  8, 12, 16],
       [25, 29, 33, 37, 41]])

In [ ]:
#then, np.multiply for multiplication (dont read the code)
np.multiply(x,y)

array([[  1,  12,  33,  64, 105],
       [ 26,  62, 108, 164, 230]])

In [ ]:
#np.divide for division (dont read the code)
np.divide(x,y)

array([[ 1.        ,  3.        ,  3.66666667,  4.        ,  4.2       ],
       [26.        , 15.5       , 12.        , 10.25      ,  9.2       ]])

In [ ]:
#np.remainder to calculate the remainder (dont read the code)
np.remainder(x,y)

array([[0, 0, 2, 0, 1],
       [0, 1, 0, 1, 1]])

In [ ]:
"""
So, These were the common functions we use to perform the mathematical operation between 2 arrays,

The in-built functions does not end here,
We have inbuilt functions to find the sine values of all the elements in the array.
Like
"""
np.sin(x)

array([[ 0.84147098, -0.2794155 , -0.99999021, -0.28790332,  0.83665564],
       [ 0.76255845, -0.40403765, -0.99177885, -0.15862267,  0.90178835]])

In [ ]:
#Similary , we have np.cos() function to find the cosines values. So,
np.cos(x)

array([[ 0.54030231,  0.96017029,  0.0044257 , -0.95765948, -0.54772926],
       [ 0.64691932,  0.91474236, -0.12796369, -0.98733928, -0.43217794]])

In [ ]:
"""

Another important function which we commonly use in our deep learning is,
finding the dot product between 2 arrays or matrices, for that, we make use of
np.dot() function, and inside the parentheses we will input the arrays for which we want to calculate
the dot product.
So,
"""
np.dot(x,y)

array([215, 590])

In [ ]:
"""
So, when we compute the dot product between two arrays, --> x & y, the resulting array have the elements as 215 & 590.

So, all the functions which we have seen till now, are the functions used to perform the matheematical operations.

In numpy, we also have the in-built function to perform aggregation as well.

To name a few, We have np.sum() function to return the array-wise sum
So, If I write as :
"""
np.sum(x)

235

In [ ]:
"""
We have the value which is equal to sum of all the elements present in the array x

Now, using the np.sum() function, We can also return the sum of the elements along its
individual axis by specifying the axis number

We can specify as, Axis = 0 to return the sum along each column, and axis = 1 to return sum along each row

To get the understanding of axis in numpy arrays, I will write it like this
"""
print("Array X is :" ,x)
print("Sum along axis = 0 is :",np.sum(x, axis = 0))
print("Sum along axis = 1 is :",np.sum(x, axis = 1))

Array X is : [[ 1  6 11 16 21]
 [26 31 36 41 46]]
Sum along axis = 0 is : [27 37 47 57 67]
Sum along axis = 1 is : [ 55 180]


In [ ]:
"""
So, 
In this way, we can make use of the np.sum() function to return the sum of the elements inside it

Similarly,
we have np.min() to return the minimum value in the array
"""
np.min(x)

1

In [ ]:
"""
This has returned the minimum value present in the entire array - 'x'

Even np.min() function can return the values across each axis 
(dont read the code)
"""
print(np.min(x, axis = 0))
print(np.min(x, axis = 1))

[ 1  6 11 16 21]
[ 1 26]


In [ ]:
"""
So, this has returned the minimum values across each axis.

Similarly,

(write in comments during screen recording below functions)

we have np.max() to find the max value across the array,
np.mean() for finding the mean,
np.median() to find the median value
np.std() to find the standard deviation

The behaviour of all these functions are exactly similar.

you can refer to numpy documentation for more information
Okay. These were some of the important aggregate functions in numpy

We can also call these aggregate functions in another way as well.

like, array_name(dot)aggregate_function 

To illustrate, I will call the sum() function on array 'x' like this
"""
x.sum()


235

In [ ]:
#Similarly, I will find the standard deviation like this
x.std()

14.361406616345072

In [ ]:
#mean of array 'x', along axis = 0 like this
x.mean(axis = 0)

array([13.5, 18.5, 23.5, 28.5, 33.5])

In [ ]:
"""
So, these were some of the important concepts we need to know in numpy package.

Now, before starting next section, I highly recommend you to complete the assignment, so that
you will have the confidence on all the topics which you have learnt till now.

See you in the next section
"""