# Autograd

In [0]:
import torch
cuda0 = torch.device('cuda:0')

In [0]:
x = torch.tensor([5], dtype = torch.float32, requires_grad = True ) 
y = torch.tensor([6], dtype = torch.float32, requires_grad = True ) 
print(x,y)

tensor([5.], requires_grad=True) tensor([6.], requires_grad=True)


In [0]:
#defining the function
z = ((x**2)*y) + (x*y)
print(z)

tensor([180.], grad_fn=<AddBackward0>)


In [0]:
#Using autograd
# Autograd to be applied on Scalars
total = torch.sum(z) # Converting to scalar

In [0]:
total

tensor(180., grad_fn=<SumBackward0>)

In [0]:
total.backward()

In [0]:
print(x.grad) 

tensor([66.])


In [0]:
print(y.grad) 

tensor([30.])


### Building intuition on Autograd

In [0]:
x = torch.randn(10,device = cuda0) 
x

tensor([-1.3878,  0.0353, -0.3580, -0.5143, -1.1193,  1.1060,  0.1161,  0.3120,
        -0.5110, -1.9720], device='cuda:0')

In [0]:
#function 
y = 1.8*x + 32  # --> wx+b
y #true values 

tensor([29.5019, 32.0635, 31.3556, 31.0742, 29.9853, 33.9909, 32.2089, 32.5616,
        31.0802, 28.4505], device='cuda:0')

In [0]:
w = torch.ones(1, requires_grad = True, device = cuda0) 
b = torch.ones(1, requires_grad = True, device = cuda0)
y_hat = w*x + b # predicted values of output

In [0]:
#Loss functions
loss = torch.sum((y_hat - y)**2)

In [0]:
loss

tensor(9402.8633, device='cuda:0', grad_fn=<SumBackward0>)

In [0]:
loss.backward() 

In [0]:
print(w.grad, b.grad) 

tensor([251.6746], device='cuda:0') tensor([-613.1312], device='cuda:0')


## Implementing Autograd

In [0]:
x = torch.randint(-100,100,(100,), dtype = torch.float32 , device = cuda0)
y = (1.8*x) + 32
w = torch.ones(1,requires_grad = True, device = cuda0 )
b = torch.ones(1,requires_grad = True, device = cuda0 ) 
y_hat = (w*x ) + b
epochs = 100000
lr = 0.000001

for i in range(epochs):
  loss = torch.sum((y_hat - y)**2) 
  loss.backward() 
  #w -= lr*w.grad --> this will be considered as relationship
  with torch.no_grad(): # this will switch off gradients
    w -= lr*w.grad
    b -= lr*b.grad
    
    #setting gradients to be zero
    w.grad.zero_()
    b.grad.zero_() 
  
  y_hat = (w*x ) + b

print(w.item(), b.item()) 
  

1.7999961376190186 31.995220184326172


In [0]:
x = torch.tensor([5], dtype = torch.float32, requires_grad = True ) 
y = torch.tensor([6], dtype = torch.float32, requires_grad = True ) 
print(x,y)
#defining the function
z = ((x**2)*y) + (x*y)
print(z)

tensor([5.], requires_grad=True) tensor([6.], requires_grad=True)
tensor([180.], grad_fn=<AddBackward0>)


In [0]:
z.backward(torch.ones_like(z))

In [0]:
x.grad

tensor([66.])

In [0]:
y.grad

tensor([30.])