In [0]:
#torch.tensor() -constructor
import torch
import numpy as np

In [0]:
list1 = ([1,2],[3,4])

In [0]:
ex_tensor = torch.tensor(list1)

In [0]:
ex_tensor

tensor([[1, 2],
        [3, 4]])

In [0]:
type(ex_tensor)

torch.Tensor

In [0]:
#Converting numpy to torch
np_tensor = torch.tensor(np.array([1,2,3,4,5,6]))

In [0]:
np_tensor

tensor([1, 2, 3, 4, 5, 6])

In [0]:
type(np_tensor)

torch.Tensor

In [0]:
#empty tensor
empty_tensor = torch.tensor([])

In [0]:
#data type - dtype
tensor_float = torch.tensor([3,4,5],dtype = torch.float32)

In [0]:
tensor_float

tensor([3., 4., 5.])

In [0]:
tensor_float.dtype

torch.float32

In [0]:
#Other important parameter for torch.tensor - Device & Requires_grad

# Ways of creating Tensors

In [0]:
#ones
x = torch.ones(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [0]:
#zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [0]:
#random.rand - random numbers between 0 and 1
torch.rand(4,2)

tensor([[0.0572, 0.7346],
        [0.8459, 0.9104],
        [0.5576, 0.1156],
        [0.1858, 0.5797]])

In [0]:
#arange
y = torch.arange(6)
y

tensor([0, 1, 2, 3, 4, 5])

In [0]:
torch.arange(5,10) #starting point as 5

tensor([5, 6, 7, 8, 9])

In [0]:
torch.arange(5,50,5) #starting point as 5, step size as 5

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [0]:
#linspace
torch.linspace(-10,10,5)

tensor([-10.,  -5.,   0.,   5.,  10.])

In [0]:
#empty tensor
torch.empty(4,3)

tensor([[1.4249e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22]])

In [0]:
#identity matrix
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [0]:
#full tensor
torch.full((2,3),5)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

### Reshape and Slicing

In [0]:
new_example = torch.arange(8)
new_example

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [0]:
new_example.shape

torch.Size([8])

In [0]:
#view
new_example.view(4,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [0]:
#reshape
new_example.reshape(2,4)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [0]:
"""
tensor.view - works only on contiguous tensors & will never copy memory. will not work on non-contiguous tensors
tensor.reshape - works on any tensor and, can make a clone if it is needed
""";

In [0]:
#slicing
x = torch.arange(8).reshape(4,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [0]:
x[2,1]

tensor(5)

In [0]:
x[2,1].item() # works only on 1 value

5

In [0]:
x[:,1].item()

ValueError: ignored

In [0]:
#returning the required range
x[2,:]

tensor([4, 5])

### Mathematical Operations on Tensors

In [0]:
x = torch.ones(3,2)
y = torch.full((3,2),3)
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])


In [0]:
print("Addition is :\n", x+y)
print("Subtraction is :\n", x-y)
print("Multiplication is :\n", x*y)
print("Division is :\n", x/y)

Addition is :
 tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])
Subtraction is :
 tensor([[-2., -2.],
        [-2., -2.],
        [-2., -2.]])
Multiplication is :
 tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])
Division is :
 tensor([[0.3333, 0.3333],
        [0.3333, 0.3333],
        [0.3333, 0.3333]])


In [0]:
#add function
z = x.add(y)

In [0]:
z

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])

In [0]:
#inplace addition - add_
z = y.add_(x)
print(z)
print(y)

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])


In [0]:
#mul_ - multiplying inplace
x.mul_(y) # store in x

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])

In [0]:
x

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])

### Pytorch - Numpy

In [0]:
x = torch.tensor(np.array([1,2,3,4,5,6,7]))
type(x)

torch.Tensor

In [0]:
x = x.numpy() # convert back to numpy
type(x) 

numpy.ndarray

In [0]:
#converting numpy array to tensor without creating the copy
z = torch.from_numpy(x) 
type(z)

torch.Tensor

In [0]:
z[0] = -10

In [0]:
z

tensor([-10,   2,   3,   4,   5,   6,   7])

In [0]:
x

array([-10,   2,   3,   4,   5,   6,   7])

### Computation time

In [0]:
#Numpy
%%time
for i in range(1000):
  x = np.random.randn(100,100)
  y = np.random.randn(100,100)
  z = x+y

CPU times: user 892 ms, sys: 83 µs, total: 892 ms
Wall time: 903 ms


In [0]:
#tensors
%%time
for i in range(1000):
  x = torch.randn(100,100)
  y = torch.randn(100,100)
  z = x+y

CPU times: user 256 ms, sys: 0 ns, total: 256 ms
Wall time: 268 ms


In [0]:
#Numpy
%%time
for i in range(1000):
  x = np.random.randn(100,100)
  y = np.random.randn(100,100)
  z = x-y

CPU times: user 874 ms, sys: 3.71 ms, total: 877 ms
Wall time: 882 ms


In [0]:
#tensors
%%time
for i in range(1000):
  x = torch.randn(100,100)
  y = torch.randn(100,100)
  z = x-y

CPU times: user 232 ms, sys: 1.87 ms, total: 234 ms
Wall time: 237 ms


In [0]:
#Numpy
%%time
for i in range(1000):
  x = np.random.randn(100,100)
  y = np.random.randn(100,100)
  z = x*y

CPU times: user 889 ms, sys: 2.47 ms, total: 891 ms
Wall time: 893 ms


In [0]:
#tensors
%%time
for i in range(1000):
  x = torch.randn(100,100)
  y = torch.randn(100,100)
  z = x*y

CPU times: user 289 ms, sys: 928 µs, total: 290 ms
Wall time: 288 ms


In [0]:
#Numpy
%%time
for i in range(10000):
  x = np.random.randn(100,100)
  y = np.random.randn(100,100)
  z = np.matmul(x,y)

CPU times: user 17.3 s, sys: 9.97 s, total: 27.2 s
Wall time: 13.9 s


In [0]:
#tensors
%%time
for i in range(10000):
  x = torch.randn(100,100)
  y = torch.randn(100,100)
  z = torch.matmul(x,y)

CPU times: user 2.79 s, sys: 84.3 ms, total: 2.88 s
Wall time: 2.83 s


# CUDA

   -  Revolutionary paralell computing architecture from NVIDIA.
   -  We can use the computing cores in Graphics Processor (GPU) for general purpose mathematical calculations
    

In [0]:
#package - torch.cuda
#check availability of cuda device
torch.cuda.is_available() 

True

In [0]:
torch.cuda.device_count() 

1

In [0]:
torch.cuda.current_device() 

0

In [0]:
#name of GPU
print(torch.cuda.get_device_name(0))

Tesla K80


## Pytorch Tensors on GPU

In [0]:
#object for cuda device
cuda0 = torch.device('cuda:0')

In [0]:
type(cuda0)

torch.device

In [0]:
a = torch.ones(2,2, device = cuda0)

In [0]:
a

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [0]:
#add parameter device for each tensor when creating for GPU
b = torch.ones(2,2,device =cuda0)
c = a+b

In [0]:
c

tensor([[2., 2.],
        [2., 2.]], device='cuda:0')

### Performance -  Numpy Vs CPU Tensors Vs GPU Tensors

In [0]:
#numpy
%%time
for i in range(100):
  x = np.random.randn(1000,1000)
  y = np.random.randn(1000,1000)
  z = x*y

CPU times: user 9.13 s, sys: 33.6 ms, total: 9.16 s
Wall time: 9.17 s


In [0]:
#CPU tensors
%%time
for i in range(100):
  x = torch.randn(1000,1000)
  y = torch.randn(1000,1000)
  z = x*y

CPU times: user 2.22 s, sys: 15.1 ms, total: 2.23 s
Wall time: 2.23 s


In [0]:
#GPU tensors
%%time
for i in range(100):
  x = torch.randn(1000,1000,device = cuda0)
  y = torch.randn(1000,1000,device =cuda0)
  z = x*y

CPU times: user 6.81 ms, sys: 1.65 ms, total: 8.46 ms
Wall time: 15.8 ms


### Matrix Multiplication

In [0]:
#numpy
%%time
for i in range(1000):
  x = np.random.randn(1000,1000)
  y = np.random.randn(1000,1000)
  z = np.matmul(x,y)

CPU times: user 4min 49s, sys: 1min 30s, total: 6min 19s
Wall time: 3min 14s


In [0]:
#CPU tensors
%%time
for i in range(1000):
  x = torch.randn(1000,1000)
  y = torch.randn(1000,1000)
  z = torch.matmul(x,y)

CPU times: user 50.4 s, sys: 249 ms, total: 50.7 s
Wall time: 50.7 s


In [0]:
#GPU tensors
%%time
for i in range(1000):
  x = torch.randn(1000,1000,device = cuda0)
  y = torch.randn(1000,1000,device =cuda0)
  z = torch.matmul(x,y)

CPU times: user 585 ms, sys: 522 ms, total: 1.11 s
Wall time: 1.12 s
